apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    name: web-v1
  name: web
  namespace: prod
spec:
  endpoints:
  - port: http
    path: /metrics
    interval: 5s
  selector:
    matchLabels:
      app: web-custom-app